people={
    'name':'helloworld',
    'age':'19',
    'city':'changde'
}
people1={
    'name':'tom',
    'age':'19',
    'city':'americal',
}
people2={
    'name':'bob',
    'age':'19',
    'city':'China',
}
People=[people2,people,people]#实现列表中存储字典
print(People)